server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088

spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        hbm2ddl:
            auto: none
        temp:
            use_jdbc_metadata_defaults: false
    show-sql: true
  datasource:
    continue-on-error: true
    hikari:
      connection-test-query: SELECT DISTINCT 1 FROM stu
      maximum-pool-size: 50
      connection-timeout: 3000
      validation-timeout: 3000
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
#    password:
    driver-class-name: com.mysql.jdbc.Driver
  output:
    ansi:
      enabled: detect
  redis:
      host: 127.0.0.1
#      password: 123456
      database: 15
      port: 6379

mybatis:
  mapper-locations: classpath*:mapper/*.xml


